fixed error when generating cmake (xmake project -k cmake) for a target that has a dependency (via add_deps) on another target.
error: method 'insert' is not callable (a nil value)

called insert as a method on a table instead of table.insert